[package]
name = "cells"
version = "0.1.0"
authors = ["Koko <mn.noppen@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.5"
timer = "0.2.0"
chrono = "0.4"
